if(NOT KITEPP_ENABLE_TICKER)
    message(FATAL_ERROR "The full lifecycle test suite requires KITEPP_ENABLE_TICKER")
endif()
enable_testing()
find_package(GTest 1.10 CONFIG REQUIRED)
find_package(Python3 COMPONENTS Interpreter REQUIRED)
set(KITE_TEST_CERT_DIR "${CMAKE_CURRENT_BINARY_DIR}/test-certificates")
execute_process(COMMAND "${Python3_EXECUTABLE}"
    "${CMAKE_CURRENT_SOURCE_DIR}/tests/make_test_certificates.py" "${KITE_TEST_CERT_DIR}"
    RESULT_VARIABLE cert_result)
if(NOT cert_result EQUAL 0)
    message(FATAL_ERROR "Unable to generate local TLS test certificates (openssl CLI required)")
endif()
file(GLOB test_files CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/unit/kite/*.cpp")
add_executable(kiteTest ${test_files})
target_link_libraries(kiteTest PRIVATE kitepp::rest GTest::gmock GTest::gtest_main GTest::gtest)
add_executable(tickerTest tests/unit/tickertest.cpp)
target_link_libraries(tickerTest PRIVATE kitepp::ticker GTest::gtest_main GTest::gtest)
add_executable(tickerLifecycleTest tests/unit/ticker_lifecycle.cpp)
target_link_libraries(tickerLifecycleTest PRIVATE kitepp::kitepp GTest::gtest_main GTest::gtest)
target_compile_definitions(tickerLifecycleTest PRIVATE KITE_TEST_CERT_DIR="${KITE_TEST_CERT_DIR}")
foreach(target kiteTest tickerTest)
    target_compile_definitions(${target} PRIVATE KITE_TEST_DATA_DIR="${CMAKE_CURRENT_SOURCE_DIR}/tests")
endforeach()
foreach(target kiteTest tickerTest tickerLifecycleTest)
    kitepp_strict_standard(${target})
endforeach()
add_test(NAME kite-test COMMAND kiteTest)
add_test(NAME ticker-test COMMAND tickerTest)
add_test(NAME ticker-lifecycle-test COMMAND tickerLifecycleTest)
set_tests_properties(kite-test ticker-test ticker-lifecycle-test PROPERTIES TIMEOUT 30)

foreach(component rest ticker umbrella standalone)
    add_executable(kitepp-${component}-consumer "tests/compile/${component}.cpp")
    if(component STREQUAL "umbrella")
        target_link_libraries(kitepp-${component}-consumer PRIVATE kitepp::kitepp)
    elseif(component STREQUAL "standalone")
        target_link_libraries(kitepp-${component}-consumer PRIVATE kitepp::models)
    else()
        target_link_libraries(kitepp-${component}-consumer PRIVATE kitepp::${component})
    endif()
    kitepp_strict_standard(kitepp-${component}-consumer)
    add_test(NAME consumer-${component} COMMAND kitepp-${component}-consumer)
endforeach()
add_executable(kitepp-two-tu tests/compile/two_tu_main.cpp
    tests/compile/two_tu_a.cpp tests/compile/two_tu_b.cpp)
target_link_libraries(kitepp-two-tu PRIVATE kitepp::rest)
kitepp_strict_standard(kitepp-two-tu)
add_test(NAME consumer-two-tu COMMAND kitepp-two-tu)
add_executable(kitepp-ticker-two-tu tests/compile/ticker_two_tu_main.cpp
    tests/compile/ticker_two_tu_a.cpp tests/compile/ticker_two_tu_b.cpp)
target_link_libraries(kitepp-ticker-two-tu PRIVATE kitepp::kitepp)
kitepp_strict_standard(kitepp-ticker-two-tu)
add_test(NAME consumer-ticker-two-tu COMMAND kitepp-ticker-two-tu)
